eureka:         #tells about the Eureka server details and its refresh time
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

spring:
    data:
        mongodb:
            database: mydatabase
            host: localhost
            port: 27017
